import {
  Flex,
  VStack,
  HStack
} from '@chakra-ui/react'


export default function ScheduleTable() {
  return (
    <Flex>
      <HStack 
        spacing="0px"
        align="top"
      >
        <VStack spacing="0px">
          <Flex
            bg="#E2E8F0"
            h="100px"
            w="80px"
          >
            8.00
          </Flex>
          <Flex
            bg="#E2E8F0"
            h="100px"
            w="80px"
          >
            9.00
          </Flex>
          <Flex
            bg="#E2E8F0"
            h="100px"
            w="80px"
          >
            10.00
          </Flex>
          <Flex
            bg="#E2E8F0"
            h="100px"
            w="80px"
          >
            11.00
          </Flex>
          <Flex
            bg="#E2E8F0"
            h="100px"
            w="80px"
          >
            12.00
          </Flex>
          <Flex
            bg="#E2E8F0"
            h="100px"
            w="80px"
          >
            13.00
          </Flex>
          <Flex
            bg="#E2E8F0"
            h="100px"
            w="80px"
          >
            14.00
          </Flex>
          <Flex
            bg="#E2E8F0"
            h="100px"
            w="80px"
          >
            15.00
          </Flex>
          <Flex
            bg="#E2E8F0"
            h="100px"
            w="80px"
          >
            16.00
          </Flex>

        </VStack>
        <VStack spacing="0px">
          <Flex
            bg="#EDF2F7"
            h="50px"
            w="50vw"
          />
          <Flex
            bg="#EDF2F7"
            h="50px"
            w="50vw"
          />
          <Flex
            bg="#EDF2F7"
            h="50px"
            w="50vw"
          />
          <Flex
            bg="#EDF2F7"
            h="50px"
            w="50vw"
          />
          <Flex
            bg="#EDF2F7"
            h="50px"
            w="50vw"
          />
          <Flex
            bg="#EDF2F7"
            h="50px"
            w="50vw"
          />
          <Flex
            bg="#EDF2F7"
            h="50px"
            w="50vw"
          />
          <Flex
            bg="#EDF2F7"
            h="50px"
            w="50vw"
          />
          <Flex
            bg="#EDF2F7"
            h="50px"
            w="50vw"
          />
          <Flex
            bg="#EDF2F7"
            h="50px"
            w="50vw"
          />
          <Flex
            bg="#EDF2F7"
            h="50px"
            w="50vw"
          />
          <Flex
            bg="#EDF2F7"
            h="50px"
            w="50vw"
          />
          <Flex
            bg="#EDF2F7"
            h="50px"
            w="50vw"
          />
          <Flex
            bg="#EDF2F7"
            h="50px"
            w="50vw"
          />
          <Flex
            bg="#EDF2F7"
            h="50px"
            w="50vw"
          />
          <Flex
            bg="#EDF2F7"
            h="50px"
            w="50vw"
          />
          <Flex
            bg="#EDF2F7"
            h="50px"
            w="50vw"
          />
          <Flex
            bg="#EDF2F7"
            h="50px"
            w="50vw"
          />
        </VStack>
      </HStack>

    </Flex>
  )
}